---
abstract: 'A Marpa-based parser for Graphviz dot files'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: '1.001006'
configure_requires:
  Module::Build: '0.421'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GraphViz2-Marpa
provides:
  GraphViz2::Marpa:
    file: lib/GraphViz2/Marpa.pm
    version: '2.02'
  GraphViz2::Marpa::Config:
    file: lib/GraphViz2/Marpa/Config.pm
    version: '2.02'
  GraphViz2::Marpa::Demo:
    file: lib/GraphViz2/Marpa/Demo.pm
    version: '2.02'
  GraphViz2::Marpa::Renderer::Graphviz:
    file: lib/GraphViz2/Marpa/Renderer/Graphviz.pm
    version: '2.02'
  GraphViz2::Marpa::Utils:
    file: lib/GraphViz2/Marpa/Utils.pm
    version: '2.02'
requires:
  Algorithm::Diff: '1.1902'
  Capture::Tiny: '0.25'
  Config: '0'
  Config::Tiny: '2.14'
  Date::Format: '2.24'
  Date::Simple: '3.03'
  File::Basename: '2.84'
  File::Copy: '2.26'
  File::HomeDir: '1'
  File::Spec: '3.4'
  File::Temp: '0.2301'
  Getopt::Long: '2.38'
  HTML::Entities::Interpolate: '1.04'
  Log::Handler: '0.71'
  Marpa::R2: '2.096'
  Moo: '1.006'
  Path::Iterator::Rule: '1.008'
  Path::Tiny: '0.061'
  Pod::Usage: '1.36'
  Text::Xslate: '1.4001'
  Tree::DAG_Node: '1.07'
  Try::Tiny: '0.09'
  Types::Standard: '1.000004'
  open: '0'
  perl: '5.014002'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/ronsavage/GraphViz2-Marpa
version: '2.02'
